from enum import Enum
from typing import Dict, Any, Optional, Union
from datetime import datetime, timezone
from pydantic import BaseModel, Field

class EventType(str, Enum):
    WEATHER_UPDATED = 'WEATHER_UPDATED'
    RAIN_PREDICTION_UPDATED = 'RAIN_PREDICTION_UPDATED'
    FLOOD_PREDICTION_UPDATED = 'FLOOD_PREDICTION_UPDATED'
    FLOOD_INTELLIGENCE_UPDATED = 'FLOOD_INTELLIGENCE_UPDATED'
    SPATIAL_RISK_UPDATED = 'SPATIAL_RISK_UPDATED'
    HISTORICAL_RISK_UPDATED = 'HISTORICAL_RISK_UPDATED'
    FORECAST_UPDATED = 'FORECAST_UPDATED'
    FORECAST_TRAJECTORY_UPDATED = 'FORECAST_TRAJECTORY_UPDATED'
    EARLY_WARNING_ESCALATED = 'EARLY_WARNING_ESCALATED'
    EARLY_WARNING_DEESCALATED = 'EARLY_WARNING_DEESCALATED'
    FORECAST_CONFIDENCE_CHANGED = 'FORECAST_CONFIDENCE_CHANGED'
    RISK_ZONE_UPDATED = 'RISK_ZONE_UPDATED'
    ALERT_CREATED = 'ALERT_CREATED'
    ALERT_UPDATED = 'ALERT_UPDATED'
    ALERT_RECOMMENDATION_CREATED = 'ALERT_RECOMMENDATION_CREATED'
    ALERT_APPROVED = 'ALERT_APPROVED'
    ALERT_REJECTED = 'ALERT_REJECTED'
    ALERT_DELIVERY_UPDATED = 'ALERT_DELIVERY_UPDATED'
    ALERT_ACKNOWLEDGED = 'ALERT_ACKNOWLEDGED'
    ALERT_EXPIRED = 'ALERT_EXPIRED'
    ALERT_ESCALATED = 'ALERT_ESCALATED'
    ALERT_DEESCALATED = 'ALERT_DEESCALATED'
    SOS_CREATED = 'SOS_CREATED'
    SOS_UPDATE_CREATED = 'SOS_UPDATE_CREATED'
    SOS_TRIAGED = 'SOS_TRIAGED'
    INCIDENT_CREATED = 'INCIDENT_CREATED'
    RESCUE_ASSIGNMENT_CREATED = 'RESCUE_ASSIGNMENT_CREATED'
    RESCUE_STATUS_UPDATED = 'RESCUE_STATUS_UPDATED'
    SHELTER_STATUS_UPDATED = 'SHELTER_STATUS_UPDATED'
    HOSPITAL_STATUS_UPDATED = 'HOSPITAL_STATUS_UPDATED'
    SIMULATION_STAGE_CHANGED = 'SIMULATION_STAGE_CHANGED'
    SYSTEM_STATUS_CHANGED = 'SYSTEM_STATUS_CHANGED'
    # Phase 5.5 Operational Intelligence Events
    INCIDENT_PRIORITY_UPDATED = 'INCIDENT_PRIORITY_UPDATED'
    RESOURCE_RECOMMENDATION_UPDATED = 'RESOURCE_RECOMMENDATION_UPDATED'
    RESOURCE_CONTENTION_DETECTED = 'RESOURCE_CONTENTION_DETECTED'
    OPERATIONAL_BOTTLENECK_DETECTED = 'OPERATIONAL_BOTTLENECK_DETECTED'
    RESOURCE_STATUS_UPDATED = 'RESOURCE_STATUS_UPDATED'
    SHELTER_CAPACITY_UPDATED = 'SHELTER_CAPACITY_UPDATED'
    HOSPITAL_CAPACITY_UPDATED = 'HOSPITAL_CAPACITY_UPDATED'
    RESPONSE_PLAN_UPDATED = 'RESPONSE_PLAN_UPDATED'
    # Phase 6 Real-Time Situational Awareness & Coordination Events
    SITUATION_UPDATED = 'SITUATION_UPDATED'
    RISK_CHANGE_DETECTED = 'RISK_CHANGE_DETECTED'
    HOTSPOT_DETECTED = 'HOTSPOT_DETECTED'
    INCIDENT_CLUSTER_UPDATED = 'INCIDENT_CLUSTER_UPDATED'
    OPERATOR_ATTENTION_UPDATED = 'OPERATOR_ATTENTION_UPDATED'
    RESOURCE_CONTENTION_UPDATED = 'RESOURCE_CONTENTION_UPDATED'
    BOTTLENECK_UPDATED = 'BOTTLENECK_UPDATED'
    OPERATIONAL_TIMELINE_UPDATED = 'OPERATIONAL_TIMELINE_UPDATED'
    AI_BRIEFING_UPDATED = 'AI_BRIEFING_UPDATED'


class DomainEvent(BaseModel):
    event: EventType
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    entity_id: Optional[Union[int, str]] = None
    entity_type: Optional[str] = None
    severity: Optional[str] = None
    data: Dict[str, Any] = Field(default_factory=dict)
